name: audiocraft_env
channels:
  - conda-forge
  - defaults
  
dependencies:
  - python=3.9.13
  - ffmpeg
  
  
  # assume user have already have git installed
  #- git  # needed for git clone if Git is not separately installed
